name: Destroy specific environment
author: etereoio
description: |-
  Action to destroy a kubernetes environmnet. Useful to recycle dynamic environments.
inputs:
  namespacePrefix:
    description: 'Prefix of any namespace deployed in to the cluster'
    required: true
    default: ''
  gcpProjectId:
    description: 'Project id where the kubernetes cluster is located'
    required: true
    default: ''
  gcpServiceAccountKey:
    description: 'Gcp service account key to use for authentication agains gcp'
    required: true
    default: ''
  gkeClusterName:
    description: 'GKE k8s cluster name'
    required: true
    default: ''
  gcpClusterZone:
    description: 'Gcp zone where the cluster is located'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Get gke cluster credentials
      shell: bash
      run: |-
        gcloud container clusters get-credentials ${{ inputs.gkeClusterName }} --zone ${{ inputs.gcpClusterZone }}
    - name: Delete specific environment
      shell: bash
      run: |-
        BRANCH_LOWER="$(echo "$GITHUB_REF" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')"

        FEAT_FULL_NAME="$(printf "%s" "${BRANCH_LOWER##*/}" )"
        FEAT_NAME="${FEAT_FULL_NAME:0:30}"
        NAMESPACE=${{ inputs.namespacePrefix }}

        if [[ "$BRANCH_LOWER" =~ ${{ env.REGEX_FEATURE_BRANCH }} ]] ; then
          export NAMESPACE+="-ft-$FEAT_NAME"
        elif [[ "$BRANCH_LOWER" =~ ${{ env.REGEX_HOTFIX_BRANCH }} ]] ; then
          export NAMESPACE+="-hot-$FEAT_NAME"
        else
          export NAMESPACE+="-$FEAT_NAME"
        fi

        kubectl delete namespace $NAMESPACE