name: Destroy specific environment
author: BillinTeam
description: |-
  Action to destroy a kubernetes environmnet. Useful to recycle dynamic environments.
inputs:
  namespacePrefix:
    description: "Prefix of any namespace deployed in to the cluster"
    required: true
    default: ""
  gkeClusterName:
    description: "GKE k8s cluster name"
    required: true
    default: ""
  gcpClusterZone:
    description: "Gcp zone where the cluster is located"
    required: true
    default: ""
outputs:
  branch_short:
    description: "The short name of the branch"
    value: ${{ steps.delete-namespace.outputs.branch_short }}
runs:
  using: "composite"
  steps:
    - name: Delete specific environment
      id: delete-namespace
      shell: bash
      run: |-
        BRANCH_LOWER="$(echo ${{ github.event.ref }} | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')"
        echo "Affected branch: "${{ github.event.ref }}
        BRANCH_TYPE=$(echo $BRANCH_LOWER | cut -d'/' -f 1)
        FEAT_FULL_NAME="$(printf "%s" "${BRANCH_LOWER##*/}" )"
        FEAT_NAME="${FEAT_FULL_NAME:0:30}"
        NAMESPACE=${{ inputs.namespacePrefix }}

        if [[ "$BRANCH_TYPE" =~ ${{ env.REGEX_FEATURE_BRANCH }} ]] ; then
          NAMESPACE+="-ft-"$FEAT_NAME
          echo "branch_short=ft-$FEAT_NAME" >> $GITHUB_OUTPUT
          echo "Deleting namespace $NAMESPACE for feature branch $BRANCH_LOWER"
          kubectl delete namespace $NAMESPACE
        elif [[ "$BRANCH_TYPE" =~ ${{ env.REGEX_HOTFIX_BRANCH }} ]] ; then
          NAMESPACE+="-hot-"$FEAT_NAME
          echo "branch_short=hot-$FEAT_NAME" >> $GITHUB_OUTPUT
          echo "Deleting namespace $NAMESPACE for hotfix branch $BRANCH_LOWER"
          kubectl delete namespace $NAMESPACE       
        else
          echo "Branch doesn't match, all fine!"
          echo "branch_short=" >> $GITHUB_OUTPUT
        fi
