name: Get deploy environment
author: BillinTeam
description: |-
  Get the k8s environment and helm config to deploy feats and development branches
inputs:
  appPrefix:
    description: "Prefix of application namespace deployed in to the cluster"
    required: true
    default: ""
  deployFromPR:
    description: "Flag that indicates the deployment will be from a Pull Request"
    required: false
    default: ""
outputs:
  namespace:
    description: "The kubernetes namespace where the application is deployed to"
    value: "${{ steps.deploy.outputs.namespace }}"
  branch_short:
    description: "The name of the branch used for environment url"
    value: "${{ steps.deploy.outputs.branch_short }}"
  helm_deploy_environment:
    description: "Which tortilla repo helmfile is used to deploy the application"
    value: "${{ steps.deploy.outputs.helm_deploy_environment }}"
runs:
  using: "composite"
  steps:
    - name: Get environment
      shell: bash
      run: |-
        if [[ "${{ inputs.deployFromPR }}" != "" ]]; then
          BRANCH_LOWER="$(echo "$GITHUB_HEAD_REF" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')"
          BRANCH_TYPE=$BRANCH_LOWER
        else
          BRANCH_LOWER="$(echo "$GITHUB_REF" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')"
          BRANCH_TYPE=$(echo $BRANCH_LOWER | cut -d'/' -f 3)
        fi

        FEAT_FULL_NAME="$(printf "%s" "${BRANCH_LOWER##*/}" )"
        FEAT_NAME="${FEAT_FULL_NAME:0:30}"
        NAMESPACE=""
        HELM_DEPLOY_ENVIRONMENT=""

        echo "BRANCH_TYPE: $BRANCH_TYPE"
        echo "${{ env.REGEX_FEATURE_BRANCH }}"

        if [[ "$BRANCH_TYPE" =~ ${{ env.REGEX_FEATURE_BRANCH }} ]] ; then
          export NAMESPACE="${{ inputs.appPrefix }}-ft-$FEAT_NAME"
          export BRANCH_SHORT="ft-"$FEAT_NAME
          export HELM_DEPLOY_ENVIRONMENT="feat"
          echo "Feature"
        elif [[ "$BRANCH_TYPE" =~ ${{ env.REGEX_HOTFIX_BRANCH }} ]] ; then
            export NAMESPACE="${{ inputs.appPrefix }}-hot-$FEAT_NAME"
            export BRANCH_SHORT="hot-"$FEAT_NAME
            export HELM_DEPLOY_ENVIRONMENT="feat"
            echo "Hotfix"
        else
          export HELM_DEPLOY_ENVIRONMENT="dev"
          echo "default branch"
        fi

        echo "BRANCH_SHORT "$BRANCH_SHORT
        echo "namespace=$(echo $NAMESPACE)" >> $GITHUB_OUTPUT
        echo "branch_short=$(echo $BRANCH_SHORT)" >> $GITHUB_OUTPUT
        echo "helm_deploy_environment=$(echo $HELM_DEPLOY_ENVIRONMENT)" >> $GITHUB_OUTPUT
