name: Continuous delivery to kubernetes cluster
author: etereoio
description: |-
  Deploy your applications to kubernetes using helm
inputs:
  helmRepoFilePath:
    description: 'Path to the encrypted helm repos file'
    required: false
    default: 'helm.repositories.yaml'
  helmfileName:
    description: 'Name of the helmfile config'
    required: false
    default: 'helmfile.yaml'
  baseDeployDir:
    description: 'Directory where different deployment enviroment folders are placed'
    required: false
    default: 'deploy'
  environment:
    description: 'Environment where to deploy the application. Must match with a the folder name inside "baseDeployDir". Inside the folder path a helmfile inside have to be placed'
    required: true
    default: ''
  namespacePrefix:
    description: 'Prefix of any namespace deployed in to the cluster'
    required: true
    default: ''
  gcpProjectId:
    description: 'Project id where the kubernetes cluster is located'
    required: true
    default: ''
  gcpServiceAccountKey:
    description: 'Gcp service account key to use for authentication agains gcp'
    required: true
    default: ''
  gkeClusterName:
    description: 'GKE k8s cluster name'
    required: true
    default: ''
  gcpClusterZone:
    description: 'Gcp zone where the cluster is located'
    required: true
    default: ''
  helmfileVersion:
    description: 'Version of helmfile'
    required: false
    default: 'v0.132.0'
  dockerImageDigest:
    description: 'Docker image tag to be placed in the helm chart values. Require replaceDockerImage attr set to true'
    required: false
    default: ''
  dockerImageDigestKeyPath:
    description: 'Yaml path in dot notation to Docker image digest value that needs to be replaced'
    required: false
    default: 'base.deployment.image.digest'
  dynamicNamespace:
    description: 'Forces deployment to a dynamic environment. The k8s namespace name comes from the github branch name that triggers the event'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Download sops binary for decrypting enc. helmfile
      shell: bash
      run: |-
        curl -L https://github.com/mozilla/sops/releases/download/v3.6.1/sops-v3.6.1.linux -O
        mv sops-v3.6.1.linux sops
        chmod +x sops
    - name: Download yq binary for parse helm repos file
      shell: bash
      run: |-
        curl -L https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O
        mv yq_linux_amd64 yq
        chmod +x ./yq
    - name: Decrypt helm repositories file using sops
      shell: bash
      run: |-
        echo "Decrypting helm repositories in ${{ inputs.helmRepoFilePath }}"
        ./sops -d ${{ inputs.helmRepoFilePath }} > ./helm.repositories.dec.yaml
    - name: Get gke cluster credentials
      shell: bash
      run: |-
        gcloud container clusters get-credentials ${{ inputs.gkeClusterName }} --zone ${{ inputs.gcpClusterZone }}
    - name: Add helm repositories
      shell: bash
      run: |-
        echo "Adding helm repositories.."
        counter=0
        REPO_FILE="$(mktemp --suffix .json)"
        ./yq r "./helm.repositories.dec.yaml" -j > "$REPO_FILE"
        echo $(jq -r '.repositories[].name' "$REPO_FILE")
        for repo in $(jq -r '.repositories[].name' "$REPO_FILE") ; do
          echo "Adding helm repo: $repo"
          HELM_LOCAL_USER="$(jq -r ".repositories[$counter].username | select (.!=null)" "$REPO_FILE")"
          HELM_LOCAL_PASS="$(jq -r ".repositories[$counter].password | select (.!=null)" "$REPO_FILE")"
          HELM_LOCAL_URL="$(jq -r ".repositories[$counter].url | select (.!=null)" "$REPO_FILE")"
          if [ -n  "$HELM_LOCAL_USER" ] ; then
            helm repo add $repo $HELM_LOCAL_URL --username \"$HELM_LOCAL_USER\" --password \"$HELM_LOCAL_PASS\"
          else
            helm repo add $repo $HELM_LOCAL_URL
          fi
          ((counter=counter+1))
        done
    - name: Download helmfile binary
      shell: bash
      run: |-
        curl -L https://github.com/roboll/helmfile/releases/download/${{ inputs.helmfileVersion }}/helmfile_linux_amd64 -O
        mv helmfile_linux_amd64 helmfile
        chmod +x ./helmfile
    - name: Install helm-secrets helm plugin
      shell: bash
      run: helm plugin install https://github.com/zendesk/helm-secrets
    - name: Syncronize helm releases using helmfile and replacing docker image digest
      shell: bash
      run: |-
        BRANCH_LOWER="$(echo "$GITHUB_REF" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')"

        FEAT_FULL_NAME="$(printf "%s" "${BRANCH_LOWER##*/}" )"
        FEAT_NAME="${FEAT_FULL_NAME:0:30}"
        NAMESPACE=${{ inputs.namespacePrefix }}

        if [[ "$BRANCH_LOWER" =~ ${{ env.REGEX_FEATURE_BRANCH }} ]] ; then
          export NAMESPACE+="-ft-$FEAT_NAME"
        elif [[ "$BRANCH_LOWER" =~ ${{ env.REGEX_HOTFIX_BRANCH }} ]] ; then
          export NAMESPACE+="-hot-$FEAT_NAME"
        elif
          export NAMESPACE+="-$FEAT_NAME"
        fi

        HELM_EXTRA_ARGS=""

        if [ "${{ inputs.dockerImageDigest}}" != "" ]; then
          HELM_EXTRA_ARGS+="--set ${{ inputs.dockerImageDigestKeyPath }}=${{ inputs.dockerImageDigest }}"
        fi

        ./helmfile --file ${{ inputs.baseDeployDir }}/${{ inputs.environment }}/${{ inputs.helmfileName }} sync $HELM_EXTRA_ARGS