name: Build and push to gcr
author: etereoio
description: |-
  Build your app docker image and push it to gcr
inputs:
  dockerfilePath:
    description: 'Path to the docker file of your application'
    required: false
    default: 'Dockerfile'
  dockerImageUrl:
    description: 'Url of the docker image'
    required: true
    default: ''
  dockerImageTag:
    description: 'Docker image tag'
    required: false
    default: "latest"
  gcpProjectId:
    description: 'Project id where the kubernetes cluster is located'
    required: true
    default: ''
  gcpServiceAccountKey:
    description: 'Gcp service account key to use for authentication against gcp'
    required: true
    default: ''
outputs:
  docker_image_sha: # id of the output
    description: 'The sha 256 of the published docker image'
    value: ${{ steps.build-docker.outputs.docker_image_sha }}
runs:
  using: "composite"
  steps:
    - name: Build and push docker image
      shell: bash
      id: build-docker
      run: |-
        gcloud auth configure-docker
        docker build . -f ${{ inputs.dockerfilePath }} -t ${{ inputs.dockerImageUrl }}
        IMAGE_URL=${{ inputs.dockerImageUrl }}:${{ inputs.dockerImageTag }}
        docker tag ${{ inputs.dockerImageUrl }} $IMAGE_URL
        docker push $IMAGE_URL
        DOCKER_IMAGE_SHA=$(docker inspect --format='{{ (index .RepoDigests 0) }}' $IMAGE_URL | cut -d'@' -f 2)
        echo "Exporting digest: "$DOCKER_IMAGE_SHA
        echo "::set-output name=docker_image_sha::$DOCKER_IMAGE_SHA"